platform :ios, '7.0'

inhibit_all_warnings!

#link_with 'MAGCoreDataExample', 'MAGCoreDataTests'

target :MAGCoreDataExample do
#    pod 'AFNetworking', '~> 2.5.4'
#    pod 'Masonry', '~> 0.6.1'
    pod 'ISO8601DateFormatter', '~> 0.7'
    pod 'MBProgressHUD', '~> 0.9.1'
end

target :MAGCoreDataTests do
    pod 'OCMock', '~> 3.1.2'
    pod 'Expecta', '~> 1.0.0'
end